### ISSUE TITLE
Landscape pages issue

### ISSUE THREAD

**Issue by AQueff** [mdahirel/PCItemplate#6]
Hi there, the third issue I faced (I am sorry if this is not the way I should use Github to tell you my problems, please feel free to tell me if I should do something else)

I have tables in landscape because I need it for a big table:
```{r tab-summary, echo=FALSE}
Sites_ordered = Sites[order(Sites$Index),]
landscape(kable(Sites_ordered[,c(3,2,12,13,14,30)], row.names = FALSE, caption = "Summary of the Site dataset", booktabs = TRUE, longtable = TRUE)) %>%
  kable_styling(full_width = FALSE, 
                #latex_options = "striped", 
                font_size = 9)
```

**The error in Rstudio:**
! LaTeX Error: Environment landscape undefined.

Erreur : LaTeX failed to compile manuscript.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See manuscript.log for more info.
De plus : Warning message:
In has_crop_tools() : 
Tool(s) not installed or not in PATH: ghostcript
-> As a result, figure cropping will be disabled.
Exécution arrêtée

**The error in the Latex log:**
! LaTeX Error: Environment landscape undefined.

I guess this would help to have the possibility to have landscape pages. I had to do that in Word and almost lost my mind to achieve it!
When I remove this landscape table... other issues appear... see next issue... :)

**Comment by mdahirel** [comment]
Hi,

As indicated here: https://community.rstudio.com/t/kableextra-landscape-latex-error-environment-landscape-undefined/12040/5, using `tinytex` should solve the problem

**Comment by AQueff** [comment]
I changed my LaTeX distribution (not so easy!) and I took the example from the link you gave me. It works fine this way.
But When I copy/paste the code for the landscape table in the .rmd code using the PCI template the problem remains.

I added \usepackage{pdflscape} in the preamble.tex file and there is no error message anymore! It works, the pages with the table are in landscape mode.

But it is far from perfect since the header and footer of the page are still in the portait mode, it's like the paper just flipped, to print the table.

So I guess adding \usepackage{pdflscape} in the preamble.tex file would be a good idea. But how to make the header and footer follow the rotating page... I guess it is still in the preamble.tex in **Headers and footers** part. Probably making two different headers with an *\if* for separating landscape header from portrait header?

**Comment by mdahirel** [comment]
Thanks for the suggestion, pdflscape now supported in the template as this may be more generally useful. However, note that more specific uses, in rmarkdown, users can "inject" the supplementary LaTeX packages they need through the Rmd file, without altering the .tex file, through the YAML header:

```
header-includes:
   - \usepackage{pdflscape}
```
for instance.

Back to your issue, the best solution is to wrap the specific table around LaTeX commands triggering the landscape switch in the Rmd document itself. The following should work as of the latest commit:

\begin{landscape}
the r chunk for this table
\end{landscape}

Note that this will likely stick the entire table on its own separate page (although since this will be used for big tables, should not be a problem)
